---
- name: Provision and configure EC2 instance for Flask web app
  hosts: webservers
  become: true
  vars_files:
    - vars.yml
  vars:
    # Set Flask app variables  
    flask_app_name: flask-app
    flask_app_port: 5000
    flask_app_secret_key: super-secret-key

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - nginx
          - gunicorn3
        state: present
    # Include task to generate config file
    - include_tasks: generate_config.yml

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ flask_app_port }}"

    - name: Clone Flask app from Git
      git:
        repo: https://github.com/johy9/flaskapp.git
        dest: /home/ubuntu/{{ flask_app_name }}
        version: master

    - name: Install Flask app requirements
      pip:
        requirements: /home/ubuntu/{{ flask_app_name }}/requirements.txt

    - name: Configure Flask app
      copy:
        src: /home/ubuntu/{{ flask_app_name }}/config.py.example
        dest: /home/ubuntu/{{ flask_app_name }}/config.py
      vars:
        flask_app_secret_key: "{{ flask_app_secret_key }}"
      notify:
        - restart gunicorn3

    - name: Configure Gunicorn3
      copy:
        src: /etc/systemd/system/gunicorn3.service
        dest: /etc/systemd/system/gunicorn3.service
      notify:
        - restart gunicorn3

    - name: Enable and start Gunicorn3 service
      systemd:
        name: gunicorn3
        enabled: yes
        state: started

    - name: Configure Nginx
      copy:
        src: /etc/nginx/sites-available/{{ flask_app_name }}
        dest: /etc/nginx/sites-available/{{ flask_app_name }}
      notify:
        - restart nginx

    - name: Enable Flask app in Nginx
      file:
        src: /etc/nginx/sites-available/{{ flask_app_name }}
        dest: /etc/nginx/sites-enabled/{{ flask_app_name }}
        state: link
      notify:
        - restart nginx

  handlers:
    - name: restart gunicorn3
      systemd:
        name: gunicorn3
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
