---
- name: Provision and configure EC2 instance for Flask web app
  hosts: webservers
  become: true
  vars_files:
    - vars.yml
  vars:
    # Set Flask app variables  
    flask_app_name: flask-app
    flask_app_port: 5000
    flask_app_secret_key: super-secret-key

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - nginx
          - gunicorn3
        state: present

    - name: Generate Flask app configuration file
      template:
        src: flask.conf.j2
        dest: /etc/systemd/system/{{ flask_app_name }}.service
      notify:
        - restart gunicorn3

    - name: Generate Flask app
      template:
        src: app.py.j2
        dest: /home/ubuntu/{{ flask_app_name }}/app.py
      notify:
        - restart gunicorn3

    - name: Define Flask app routes
      block:
        - name: Define home page route
          lineinfile:
            path: /home/ubuntu/{{ flask_app_name }}/app.py
            line: '    @app.route("/")\n    def hello():\n        return "{{
              flask_app_message }}"'
      become: yes
      notify:
        - restart gunicorn3

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ flask_app_port }}"

    - name: Clone Flask app from Git
      git:
        repo: https://github.com/johy9/flaskapp.git
        dest: /home/ubuntu/{{ flask_app_name }}
        version: main

    - name: Install Flask app requirements
      pip:
        requirements: /home/ubuntu/{{ flask_app_name }}/requirements.txt

    - name: Configure Flask app
      copy:
        src: /home/ubuntu/{{ flask_app_name }}/config.py.example
        dest: /home/ubuntu/{{ flask_app_name }}/config.py
      vars:
        flask_app_secret_key: "{{ flask_app_secret_key }}"
      notify:
        - restart gunicorn3

    - name: Configure Gunicorn3
      copy:
        src: /etc/systemd/system/gunicorn3.service
        dest: /etc/systemd/system/gunicorn3.service
      notify:
        - restart gunicorn3

    - name: Enable and start Gunicorn3 service
      systemd:
        name: gunicorn3
        enabled: yes
        state: started

    - name: Configure Nginx
      copy:
        src: /etc/nginx/sites-available/{{ flask_app_name }}
        dest: /etc/nginx/sites-available/{{ flask_app_name }}
      notify:
        - restart nginx

    - name: Enable Flask app in Nginx
      file:
        src: /etc/nginx/sites-available/{{ flask_app_name }}
        dest: /etc/nginx/sites-enabled/{{ flask_app_name }}
        state: link
      notify:
        - restart nginx

    - name: Restart Flask app
      systemd:
        name:
          - nginx
          - gunicorn3
        state: restarted
...
