# Ansible playbook for deploying a Flask app
---
# Install system apt packages
- hosts: webservers
  become: yes
  become_method: sudo

  tasks: 
   - name: install Python3
     packages:   
     - python3.8-venv
     - Python3-pip
     - python3-dev
     - nginx
     state: present
     update_cache: yes
