---
- name: Deploy Flask app
  hosts: webservers
  remote_user: root
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
  
    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - git
        state: present
      become: yes
  
    - name: Create virtual environment
      command: python3 -m venv /opt/myappp/env
      become: yes
  
    - name: Activate virtual environment
      command: /bin/bash -c "source /opt/myappp/env/bin/activate"
      become: yes

    - name: Clone Git repository
      git:
        repo: https://github.com/johy9/flaskapp.git
        dest: /opt/myappp
      become: yes
      
    - name: Install dependencies using requirements.txt
      pip:
        requirements: /opt/myappp/requirements.txt
        executable: /opt/myappp/env/bin/pip
  
    - name: Install flask using pip
      #var: ansible_command
      pip:
        name: flask
        executable: /opt/myappp/env/bin/pip
          #state: present
      become: yes

    - name: Allow incoming traffic on port 5000
      ufw:
        rule: allow
        proto: tcp
        port: 5000
        comment: "Allow incoming traffic to Flask app"
      become: yes

    - name: Restart UFW
      systemd:
        name: ufw
        state: restarted
      become: yes
        

    - name: Start Flask app
      become: true
      command: /bin/bash -c "source /opt/myappp/env/bin/activate && export FLASK_APP=/opt/myappp/app.py && /opt/myappp/env/bin/flask run --host=0.0.0.0 &"
      async: 0
      poll: 0
